all: program

program: certTestBr.c
	gcc -Wall certTestBr.c -lmiracl -o certTestBr

help:
	@echo "Use make execute to execute with default certificates cert1 and cert2, simply make to compile and make clean to clean!"
